blank_issues_enabled: false

contact_links:
- name: Chat 💬
  url: https://adoptopenjdk.net/slack.html
  about: "Join our Slack channel #support to get help diagnosing your problems."

- name: Commercial support 🏥
  url: https://adoptopenjdk.net/support.html#commercial-support
  about: Commercial support options for AdoptOpenJDK

- name: JDK Bug System ☕
  url: https://bugs.openjdk.java.net/secure/Dashboard.jspa
  about: You can search for known bugs in the JDK Bug System.
